// Enhanced donation data with proper structure for testing

export const pendingDonations = [
  {
    id: 1,
    medicine: 'باراسيتامول 500 مجم',
    medicineEn: 'Paracetamol 500mg',
    quantity: 2,
    donor: 'أحمد محمد علي',
    donorEn: 'Ahmed Mohammed Ali',
    donatedAt: '2024-01-15',
    status: 'pending_assignment',
    eligiblePatients: 3,
    urgency: 'medium',
    donorMessage: 'أتمنى أن تصل هذه الأدوية للمحتاجين. الأدوية لم تستعمل وصالحة حتى 2026.'
  },
  {
    id: 2,
    medicine: 'أنسولين سريع المفعول',
    medicineEn: 'Fast-Acting Insulin',
    quantity: 1,
    donor: 'فاطمة أحمد علي',
    donorEn: 'Fatima Ahmed Ali',
    donatedAt: '2024-01-14',
    status: 'pending_assignment',
    eligiblePatients: 2,
    urgency: 'high',
    donorMessage: 'Insulin for diabetes patients. Please ensure it reaches someone who truly needs it.'
  },
  {
    id: 3,
    medicine: 'فيتامين د للأطفال',
    medicineEn: 'Children Vitamin D',
    quantity: 3,
    donor: 'محمد أحمد حسن',
    donorEn: 'Mohammed Ahmed Hassan',
    donatedAt: '2024-01-13',
    status: 'assigned',
    assignedTo: 'مريم إبراهيم',
    assignedToEn: 'Mariam Ibrahim',
    urgency: 'low'
  }
];

export const eligiblePatients = [
  {
    id: 1,
    name: 'مريم إبراهيم أحمد',
    nameEn: 'Mariam Ibrahim Ahmed',
    age: 34,
    condition: 'السكري النوع الأول',
    conditionEn: 'Type 1 Diabetes',
    financialStatus: 'دخل محدود',
    financialStatusEn: 'Limited Income',
    medicalPriority: 'عالية',
    medicalPriorityEn: 'High',
    lastVisit: '2024-01-10',
    phone: '+249123456789',
    notes: 'تحتاج الأنسولين بشكل دوري ولديها صعوبة في تحمل التكاليف'
  },
  {
    id: 2,
    name: 'عبدالله أحمد محمد',
    nameEn: 'Abdullah Ahmed Mohammed',
    age: 28,
    condition: 'آلام مزمنة',
    conditionEn: 'Chronic Pain',
    financialStatus: 'دخل محدود',
    financialStatusEn: 'Limited Income',
    medicalPriority: 'متوسطة',
    medicalPriorityEn: 'Medium',
    lastVisit: '2024-01-08',
    phone: '+249123456790',
    notes: 'يحتاج مسكنات بانتظام'
  },
  {
    id: 3,
    name: 'سارة محمد عثمان',
    nameEn: 'Sara Mohammed Osman',
    age: 6,
    condition: 'مشاكل تنفسية متكررة',
    conditionEn: 'Recurring Respiratory Issues',
    financialStatus: 'أسرة محتاجة',
    financialStatusEn: 'Needy Family',
    medicalPriority: 'متوسطة',
    medicalPriorityEn: 'Medium',
    lastVisit: '2024-01-05',
    phone: '+249123456791',
    notes: 'طفلة تحتاج أدوية السعال بانتظام'
  },
  {
    id: 4,
    name: 'خالد عبدالرحمن',
    nameEn: 'Khalid Abdulrahman',
    age: 45,
    condition: 'ضغط الدم المرتفع',
    conditionEn: 'High Blood Pressure',
    financialStatus: 'دخل محدود',
    financialStatusEn: 'Limited Income',
    medicalPriority: 'عالية',
    medicalPriorityEn: 'High',
    lastVisit: '2024-01-03',
    phone: '+249123456792',
    notes: 'يحتاج أدوية الضغط بشكل مستمر'
  },
  {
    id: 5,
    name: 'أميرة حسن علي',
    nameEn: 'Amira Hassan Ali',
    age: 52,
    condition: 'التهاب المفاصل',
    conditionEn: 'Arthritis',
    financialStatus: 'أرملة بدون دخل',
    financialStatusEn: 'Widow Without Income',
    medicalPriority: 'متوسطة',
    medicalPriorityEn: 'Medium',
    lastVisit: '2024-01-01',
    phone: '+249123456793',
    notes: 'تحتاج أدوية مضادة للالتهابات'
  }
];

// Sample donation requests from patients
export const donationRequests = [
  {
    id: 1,
    patientId: 1,
    medicine: 'أنسولين سريع المفعول',
    medicineEn: 'Fast-Acting Insulin',
    quantity: 2,
    urgency: 'high',
    reason: 'انتهت الكمية المتوفرة ولا أستطيع شراء جديدة',
    reasonEn: 'Ran out of supply and cannot afford to buy new ones',
    requestDate: '2024-01-12',
    status: 'pending'
  },
  {
    id: 2,
    patientId: 3,
    medicine: 'شراب السعال للأطفال',
    medicineEn: 'Children Cough Syrup',
    quantity: 1,
    urgency: 'medium',
    reason: 'ابنتي تحتاج الدواء وراتبي لا يكفي هذا الشهر',
    reasonEn: 'My daughter needs the medicine and my salary is not enough this month',
    requestDate: '2024-01-10',
    status: 'approved'
  }
];

// Participating pharmacies for donation program
export const participatingPharmacies = [
  {
    id: 1,
    name: 'صيدلية النيل الأزرق',
    nameEn: 'Blue Nile Pharmacy',
    address: 'الخرطوم - شارع النيل',
    addressEn: 'Khartoum - Nile Street',
    phone: '+249155123456',
    distance: '0.8 كم',
    distanceEn: '0.8 km',
    rating: 4.8,
    donationsReceived: 45,
    donationsDistributed: 42,
    availability: 'متاح دائماً',
    availabilityEn: 'Always Available',
    coordinates: { lat: 15.5518, lng: 32.5324 },
    operatingHours: '8:00 ص - 10:00 م',
    operatingHoursEn: '8:00 AM - 10:00 PM',
    specialServices: ['توصيل مجاني للتبرعات', 'استشارات مجانية'],
    specialServicesEn: ['Free delivery for donations', 'Free consultations']
  },
  {
    id: 2,
    name: 'صيدلية الصحة المتكاملة',
    nameEn: 'Integrated Health Pharmacy',
    address: 'أم درمان - شارع الثورة',
    addressEn: 'Omdurman - Al-Thawra Street',
    phone: '+249155234567',
    distance: '1.2 كم',
    distanceEn: '1.2 km',
    rating: 4.9,
    donationsReceived: 38,
    donationsDistributed: 35,
    availability: 'متاح',
    availabilityEn: 'Available',
    coordinates: { lat: 15.6440, lng: 32.4772 },
    operatingHours: '9:00 ص - 9:00 م',
    operatingHoursEn: '9:00 AM - 9:00 PM',
    specialServices: ['تخزين بارد للأدوية', 'فحص مجاني للأدوية'],
    specialServicesEn: ['Cold storage for medicines', 'Free medicine verification']
  },
  {
    id: 3,
    name: 'صيدلية الرحمة',
    nameEn: 'Al-Rahma Pharmacy',
    address: 'الخرطوم بحري - السوق الكبير',
    addressEn: 'Khartoum North - Grand Market',
    phone: '+249155345678',
    distance: '2.1 كم',
    distanceEn: '2.1 km',
    rating: 4.7,
    donationsReceived: 29,
    donationsDistributed: 28,
    availability: 'متاح',
    availabilityEn: 'Available',
    coordinates: { lat: 15.5892, lng: 32.5342 },
    operatingHours: '8:30 ص - 9:30 م',
    operatingHoursEn: '8:30 AM - 9:30 PM',
    specialServices: ['برنامج ولاء للمتبرعين', 'خصومات للمحتاجين'],
    specialServicesEn: ['Donor loyalty program', 'Discounts for needy patients']
  },
  {
    id: 4,
    name: 'صيدلية الشفاء',
    nameEn: 'Al-Shifa Pharmacy',
    address: 'الخرطوم - العمارات',
    addressEn: 'Khartoum - Al-Amarat',
    phone: '+249155456789',
    distance: '3.5 كم',
    distanceEn: '3.5 km',
    rating: 4.6,
    donationsReceived: 22,
    donationsDistributed: 20,
    availability: 'محدود',
    availabilityEn: 'Limited',
    coordinates: { lat: 15.5200, lng: 32.5500 },
    operatingHours: '9:00 ص - 8:00 م',
    operatingHoursEn: '9:00 AM - 8:00 PM',
    specialServices: ['استشارات صيدلية متخصصة', 'توعية صحية'],
    specialServicesEn: ['Specialized pharmaceutical consultations', 'Health awareness']
  }
];

// Available medicines for donation
export const donationMedicines = [
  {
    id: 1,
    name: 'باراسيتامول 500 مجم',
    nameEn: 'Paracetamol 500mg',
    category: 'مسكنات الألم',
    categoryEn: 'Pain Relief',
    description: 'مسكن للألم وخافض للحرارة',
    descriptionEn: 'Pain reliever and fever reducer',
    commonUses: ['صداع', 'حمى', 'آلام عامة'],
    commonUsesEn: ['Headache', 'Fever', 'General pain'],
    demand: 'عالي',
    demandEn: 'High',
    urgencyLevel: 'medium',
    estimatedValue: 15,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 48,
    distributionCount: 45,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=200&h=200&fit=crop'
  },
  {
    id: 2,
    name: 'أنسولين سريع المفعول',
    nameEn: 'Fast-Acting Insulin',
    category: 'أدوية السكري',
    categoryEn: 'Diabetes Medication',
    description: 'أنسولين للتحكم في مستوى السكر',
    descriptionEn: 'Insulin for blood sugar control',
    commonUses: ['السكري النوع الأول', 'السكري النوع الثاني'],
    commonUsesEn: ['Type 1 Diabetes', 'Type 2 Diabetes'],
    demand: 'عالي جداً',
    demandEn: 'Very High',
    urgencyLevel: 'high',
    estimatedValue: 120,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 15,
    distributionCount: 15,
    image: 'https://images.unsplash.com/photo-1550572017-cdefed14b9c1?w=200&h=200&fit=crop'
  },
  {
    id: 3,
    name: 'فيتامين د للأطفال',
    nameEn: 'Children Vitamin D',
    category: 'فيتامينات',
    categoryEn: 'Vitamins',
    description: 'فيتامين د للنمو الصحي للأطفال',
    descriptionEn: 'Vitamin D for healthy child development',
    commonUses: ['نقص فيتامين د', 'تقوية العظام', 'النمو'],
    commonUsesEn: ['Vitamin D deficiency', 'Bone strengthening', 'Growth'],
    demand: 'متوسط',
    demandEn: 'Medium',
    urgencyLevel: 'low',
    estimatedValue: 35,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 32,
    distributionCount: 28,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=200&h=200&fit=crop'
  },
  {
    id: 4,
    name: 'أدوية ضغط الدم',
    nameEn: 'Blood Pressure Medication',
    category: 'أدوية القلب والأوعية',
    categoryEn: 'Cardiovascular Medicine',
    description: 'أدوية للسيطرة على ضغط الدم المرتفع',
    descriptionEn: 'Medication for high blood pressure control',
    commonUses: ['ضغط الدم المرتفع', 'أمراض القلب'],
    commonUsesEn: ['High blood pressure', 'Heart disease'],
    demand: 'عالي',
    demandEn: 'High',
    urgencyLevel: 'high',
    estimatedValue: 85,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 25,
    distributionCount: 23,
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=200&h=200&fit=crop'
  },
  {
    id: 5,
    name: 'مضادات الالتهاب',
    nameEn: 'Anti-inflammatory Medication',
    category: 'مضادات الالتهاب',
    categoryEn: 'Anti-inflammatory',
    description: 'أدوية لعلاج الالتهابات والآلام',
    descriptionEn: 'Medication for inflammation and pain treatment',
    commonUses: ['التهاب المفاصل', 'آلام العضلات', 'التهابات عامة'],
    commonUsesEn: ['Arthritis', 'Muscle pain', 'General inflammation'],
    demand: 'متوسط',
    demandEn: 'Medium',
    urgencyLevel: 'medium',
    estimatedValue: 45,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 18,
    distributionCount: 16,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=200&h=200&fit=crop'
  },
  {
    id: 6,
    name: 'شراب السعال للأطفال',
    nameEn: 'Children Cough Syrup',
    category: 'أدوية الجهاز التنفسي',
    categoryEn: 'Respiratory Medicine',
    description: 'شراب آمن لعلاج السعال عند الأطفال',
    descriptionEn: 'Safe syrup for treating children cough',
    commonUses: ['السعال', 'نزلات البرد', 'التهاب الحلق'],
    commonUsesEn: ['Cough', 'Common cold', 'Sore throat'],
    demand: 'متوسط',
    demandEn: 'Medium',
    urgencyLevel: 'low',
    estimatedValue: 25,
    currency: 'ج.س',
    currencyEn: 'SDG',
    donationCount: 35,
    distributionCount: 32,
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&h=200&fit=crop'
  }
];

// Donation statistics for dashboard
export const donationStats = {
  totalDonations: 203,
  totalDistributed: 189,
  totalValue: 12450,
  activeDonors: 89,
  beneficiaries: 156,
  participatingPharmacies: participatingPharmacies.length,
  averageResponseTime: '2.3 ساعة',
  averageResponseTimeEn: '2.3 hours',
  successRate: 93,
  monthlyGrowth: 15
};